// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "PCLType.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



void
PCLType::Color::operator>>= (cdrStream &_n) const
{
  r >>= _n;
  g >>= _n;
  b >>= _n;

}

void
PCLType::Color::operator<<= (cdrStream &_n)
{
  (::CORBA::UShort&)r <<= _n;
  (::CORBA::UShort&)g <<= _n;
  (::CORBA::UShort&)b <<= _n;

}

void
PCLType::PointXYZRGB::operator>>= (cdrStream &_n) const
{
  (const RTC::Point3D&) point >>= _n;
  (const Color&) colour >>= _n;

}

void
PCLType::PointXYZRGB::operator<<= (cdrStream &_n)
{
  (RTC::Point3D&)point <<= _n;
  (Color&)colour <<= _n;

}

void
PCLType::PointCloud::operator>>= (cdrStream &_n) const
{
  (const RTC::Time&) tm >>= _n;
  (const PointXYZRGBList&) pc >>= _n;
  height >>= _n;
  width >>= _n;
  _n.marshalBoolean(is_dense);

}

void
PCLType::PointCloud::operator<<= (cdrStream &_n)
{
  (RTC::Time&)tm <<= _n;
  (PointXYZRGBList&)pc <<= _n;
  (::CORBA::ULong&)height <<= _n;
  (::CORBA::ULong&)width <<= _n;
  is_dense = _n.unmarshalBoolean();

}

